### ISSUE TITLE
ParcelablePlease Intelij plugin error

### ISSUE THREAD

**Issue by aradomski** [sockeqwe/ParcelablePlease#5]
```
cannot create class "com.hannesdorfmann.parcelableplease.plugin.ParcelablePleaseAction" [Plugin: com.hannesdorfmann.parcelableplease.plugin]: cannot create class "com.hannesdorfmann.parcelableplease.plugin.ParcelablePleaseAction" [Plugin: com.hannesdorfmann.parcelableplease.plugin]
com.intellij.diagnostic.PluginException: cannot create class "com.hannesdorfmann.parcelableplease.plugin.ParcelablePleaseAction" [Plugin: com.hannesdorfmann.parcelableplease.plugin]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:287)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:239)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getAction(ActionManagerImpl.java:232)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.unStub(DefaultActionGroup.java:345)
	at com.intellij.openapi.actionSystem.DefaultActionGroup.getChildren(DefaultActionGroup.java:303)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1261)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$5.compute(ActionManagerImpl.java:1254)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:932)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1254)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1248)
	at com.intellij.codeInsight.generation.actions.GenerateAction.preload(GenerateAction.java:91)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1266)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1269)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActionGroup(ActionManagerImpl.java:1248)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.doPreloadActions(ActionManagerImpl.java:1236)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.access$200(ActionManagerImpl.java:73)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$4.run(ActionManagerImpl.java:1220)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
Caused by: com.intellij.diagnostic.PluginException: com/hannesdorfmann/parcelableplease/plugin/ParcelablePleaseAction : Unsupported major.minor version 52.0 [Plugin: com.hannesdorfmann.parcelableplease.plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convert(ActionManagerImpl.java:262)
	... 23 more
Caused by: java.lang.UnsupportedClassVersionError: com/hannesdorfmann/parcelableplease/plugin/ParcelablePleaseAction : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:195)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:191)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:167)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:124)
	... 29 more
```
```
12:46:14 PluginException: cannot create class "com.hannesdorfmann.parcelableplease.plugin.ParcelablePleaseAction" [Plugin: com.hannesdorfmann.parcelableplease.plugin]: cannot create class "com.hannesdorfmann.parcelableplease.plugin.ParcelablePleaseAction" [Plugin: com.hannesdorfmann.parcelableplease.plugin]
12:46:46 Throwable: Null child action in group Generate () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=generateParcelablePlease
```
OS: Linux Mint 16
AS: 0.9.3

Exception occures everytime when I press **alt + insert** to generate something. ParcelablePlease doesn't even occurs on list.

**Comment by sockeqwe** [comment]
I can't reproduce this issue
